### ISSUE TITLE
ADD pose_resnet

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models-tflite#30]
下記のONNXモデルから、tflite (float)とtflite (int8)を生成してサンプルを作成する。
https://github.com/axinc-ai/ailia-models/tree/master/pose_estimation/pose_resnet

最終目的はtflite版のmodel-zooを作成することです。

![2](https://user-images.githubusercontent.com/38881041/222651287-a409f94e-b8a4-40c7-b823-e1bc4f944d03.png)

そのために、onnxをtfliteに変換します。

![3](https://user-images.githubusercontent.com/38881041/222651346-5ffed991-4635-4acc-aef1-dde597f602ce.png)

**Comment by kyakuno** [comment]
変換フローの説明。
https://github.com/axinc-ai/ailia-models-tflite/issues/41

**Comment by kyakuno** [comment]
1. onnxをtflite (float)に変換
2. onnxのサンプルをコピペしてサンプル作成
3. tflite (int8)を作成
4. サンプルのint8対応

前処理のyoloはこのリポジトリにある変換済みのモデルを使ってください。

**Comment by kyakuno** [comment]
サンプルはとりあえず、公式のtensorflow.liteを使ってください。サンプルの実行時に—tfliteオプションを付与すると、ailiaではなく公式のapiで推論します。

**Comment by kyakuno** [comment]
saved model -> tflite (int8)のサンプル
https://github.com/axinc-ai/export-to-tflite

**Comment by kyakuno** [comment]
ailiaは下記のURLから入手してください。
https://axip-console.appspot.com/trial/terms/AILIA-TFLITE

**Comment by kyakuno** [comment]
OpenVino2TensorFlowの解説記事
https://qiita.com/PINTO/items/7a0bcaacc77bb5d6abb1

**Comment by kyakuno** [comment]
savedmodelの作成時に、tensorflow.SavedModel exceeds maximum protobuf size of 2GBというエラーが出るとのこと。

**Comment by craft-c** [comment]
openvino2tensorflow を用いる方法で、再度 .onnx → openvino → saved_model の変換を試したところ、エラーは出ませんでした。("○○は非推奨です" のようなWarningはいくつか出ましたが)

詰まっているmidas #31 のint8変換はいったん保留にして、pose_resnetのサンプル作成を進めてみたいと思います。

**Comment by craft-c** [comment]
### 進捗報告
- 置き換え完了
- 人を検出する部分の動作は良好
- 骨格推定が上手くいかない
モデルの問題か、画像の前後処理の問題かの切り分けが必要
![output](https://user-images.githubusercontent.com/66067238/234527790-999bb2e6-f3cc-4320-a4cb-b8d4888834b7.png)

**Comment by craft-c** [comment]
### 進捗報告

サンプルスクリプト完成 
(画像・動画 共に floatモデルでの動作確認完了)

![output](https://user-images.githubusercontent.com/66067238/234864775-34093243-e05f-48cc-a934-d9773f6405f7.png)

**Comment by craft-c** [comment]
@kyakuno 

サンプルはほぼ完成しました。
残りの問題は以下の1点です。
**・float32モデル と ailia-tflite runtime の組み合わせで 精度が出ない**

[float32モデル]
表に示すように、公式TFlite だと精度良く推論できますが、
ailia-tflite runtime　だと精度が出ません。
また、onnx2tfで変換したモデルの方は、PADV2エラーが出ます。
公式TFliteでは上手く推論できるので、ailia側の問題でしょうか？

[int8モデル]
openvino2tensorflowで変換したモデルの精度は良好です。
onnx2tfで変換したモデルの精度は良くない & PADV2 エラーが出ます。

とりあえず現状でPRで良いでしょうか？


pose_resnetブランチは
[こちら](https://github.com/axinc-ai/ailia-models-tflite/tree/pose_resnet/pose_estimation/pose_resnet)

現時点で公開するとすれば、
float32は onnx2tf で変換したモデルを
int8は openvino2tensorflow で変換したモデルを参照してもらいたいです。
DLは[こちら](https://drive.google.com/drive/folders/15ZWby_1I0_WN87NwyoWbCD4SZ0vSB60X?usp=share_link)から
※なお、物体検出は yolov3-tiny のモデルを使用しています。

![image](https://user-images.githubusercontent.com/66067238/235063121-01919864-7d33-4ff1-aa60-876b01299d11.png)

![image](https://user-images.githubusercontent.com/66067238/235063143-ecf68321-0507-4725-ac97-8f6d2aaa51b3.png)

**Comment by kyakuno** [comment]
@craft-c エクスポート、ありがとうございます。PADV2は次回のailia TFLite Runtimeで対応しますので、公式のtensorflowで動いていれば問題ありません。PRいただければと思います。
