### ISSUE TITLE
ADD midas

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models-tflite#31]
下記のONNXからtflite (float)とtflite (int8)を追加する。
https://github.com/axinc-ai/ailia-models/tree/master/depth_estimation/midas

**Comment by kyakuno** [comment]
#30 と同じ手順で進めていただければと思います。

**Comment by craft-c** [comment]
入出力画像のリサイズについてメモ

画像のアスペクト比を **"維持せずに"** リサイズを行っています。
アスペクト比を維持したままだと、パディング部分も推論されてしまい、良好な結果が得られません。

![image](https://user-images.githubusercontent.com/66067238/224905520-60cde6e8-6caa-415d-be82-0ec276dc4031.png)
![image](https://user-images.githubusercontent.com/66067238/224905583-a20d1281-3a39-4378-9e1b-d65dc9982bb4.png)

**Comment by craft-c** [comment]
学習モデル .tflite(int8) 版について [03/10 14:45 現在]

COCO2017データセット 5000枚で 学習した (int8)版の学習モデルの精度が良くありません。
もう一度(int8)版の学習モデルの生成コードを見直してみます。
![image](https://user-images.githubusercontent.com/66067238/224907666-75ae34bb-7245-467d-a2fe-7d55a127dd70.png)

**Comment by craft-c** [comment]
残りの作業
・推論フレームワークをailia-TF runtime にも対応させる。
・(int8)版の .tflite 学習モデル 再生成
　　↓
・Readme等ドキュメントを作成し、GitHubへ

**Comment by craft-c** [comment]
（メモ）
・onnx2tfを用いて onnx → .tflite (float32)(int8) へ変換

　midas.onnx の入力は dynamic dimension になっているので、`-ois input:1,3,384,384` オプションが必要。
　また、saved_modelの出力のためには `-dgc' オプション も必要
結果として、`onnx2tf -i midas.onnx -ois input:1,3,384,384 -dgc` のコマンドで、.tflite(float32) 及び saved_model が出力される

**Comment by kyakuno** [comment]
PADV2については、ailia TFLite Runtime側の更新で対応しようと思いますので、ailiaでは動かなくても問題ありません。

**Comment by craft-c** [comment]
[現状メモ]
・onnx2tf を用いて変換した .tflite(int8) のモデルで精度が出ない。
・また、1枚の画像推論に要する時間が異様に長い(15分～)。
→再度 int8 版の モデル生成を見直してみる。

@kyakuno 
・float32の精度は良好なので、いったんfloat32版のみでPRしても良いでしょうか？

**Comment by kyakuno** [comment]
@craft-c キャリブレーション画像にテスト用の入力画像を使った場合に、どのような出力が得られるか確認いただくことは可能でしょうか。キャリブレーション画像に入力画像を使うと精度が出る場合は、キャリブレーション用のデータセットを別のものにした方がいいかもしれません。tfliteは内部的に、floatで推論して、tensorのmin/maxを計算してそのレンジでint8に量子化しているため、テスト用の推論画像1枚を使って量子化して推論するのが、テスト用の画像では最も精度が出ると思います。ただし、汎化性能はなくなるので、あくまでテスト用になります。

**Comment by kyakuno** [comment]
@craft-c また、コードも確認したいため、一旦、現状でPRをいただければと思います。合わせて、convertというサブフォルダを作成し、変換に使用したスクリプトも同梱いただければと思います。

ailia-models-tflite/depth_estimation/midas/midas.py
ailia-models-tflite/depth_estimation/midas/convert/convert.sh : openvino2tensorflowの呼び出しスクリプト 
ailia-models-tflite/depth_estimation/midas/convert/quantize.py : 量子化スクリプト（キャリブレーションディレクトリは引数で与える）

**Comment by kyakuno** [comment]
処理時間については、Google公式のtensorflowがIntelに対応していないために重いだけですので、ailia tflite runtimeが対応すれば高速化される想定です。

**Comment by craft-c** [comment]
先ほど示した結果は **"onnx2tf"** を用いて変換したモデルなのですが、int8版の.tfliteモデルについて、僕が少し勘違いしていたかもしれません。

1枚目の図に示すように、onnx2tfを用いて midas.onnx を変換すると、saved_model内に 「midas_full_integer_quant.tffile」が生成されます。僕はこのファイルが int8版の.tfliteモデル だと思っていたのですが、これは間違いでしょうか？

要するに2枚目の画像のように、この「saved_model」+「キャリブレーション画像」を用いて量子化したファイルが int8版の.tfliteモデルになるのでしょうか？ 

![image](https://user-images.githubusercontent.com/66067238/225263127-346f4d4a-a9bd-495a-b710-38ec393f35a2.png)
![image](https://user-images.githubusercontent.com/66067238/225263209-fd9c5f1e-d0b2-4d9d-97f5-2561e3e07322.png)

**Comment by craft-c** [comment]
@kyakuno 
あと、確認なのですが、PRは main へ向けて行えば良いですか？
それとも開発用の他のブランチですか？

一応、コードの確認だけでしたら、midasブランチをGitHubへPushしてあるので、そちらから確認できます。
https://github.com/axinc-ai/ailia-models-tflite/tree/midas

**Comment by craft-c** [comment]
@kokuno1122 

kokunoさんへ

初めまして。
先々週からaxellのインターンでお世話になっています。
tanikubo です。

midasサンプルにおいて、
.onnx ファイルを .tflite(int8) へ変換する作業で詰まっています。
kokunoさんが issue#47 [ADD U2Net] で同様の作業をされていたので質問があります。

・まず、私はsaved_modelの出力に onnx2tf を用いているのですが、コマンドを実行する際、引数の指定において注意する点はありますか？
　私はmidas.onnx の変換に際して、onnx2tf -i midas.onnx -osd -ois input:1,3,384,384 -dgc のコマンドを実行しました。

・可能でしたら、出力されたsaved_modelを量子化する際に使用したpythonスクリプト を見せていただけませんか？

よろしくお願いします。

**Comment by kokuno1122** [comment]
@craft-c 
はじめまして。ご連絡ありがとうございます！
私も量子化は今回のPRではじめて実施したため、知見があるわけではないので、
適切な回答できないかもしれません。
コマンドで色々試してみて、精度が出るものを採用したという感じです。

使用したコマンドは下記です。
`onnx2tf -i ~.onnx -oiqt`

量子化のサンプルは、[こちら](https://github.com/axinc-ai/export-to-tflite/blob/main/tensorflow2/quantize.py)が参考になると思います！

**Comment by kokuno1122** [comment]
@craft-c 
numpyでキャリブレーションのデータを作成しておいて、
それをコマンドで読み込ませる方法もあるようです。
下記のページで"qcind"検索してみてください！
https://github.com/PINTO0309/onnx2tf

**Comment by craft-c** [comment]
了解しました！
ありがとうございます。

**Comment by craft-c** [comment]
@kokuno1122 
.tflite(int8) 
midasサンプルにおいては、
「onnx2tf」を使う方法よりも「openvino2tensorflow」を使う方法の方が精度が出ているように思います。
![image](https://user-images.githubusercontent.com/66067238/225835770-487ffdcd-94d9-476b-a22a-2551af383f2e.png)
![image](https://user-images.githubusercontent.com/66067238/225835808-56df4758-1250-4928-b106-1eba9a57ade7.png)

**Comment by craft-c** [comment]
@kokuno1122 

また、"-qcind"オプション を使ってキャリブレーションする方法については、MEAN と STD に何を指定するのかよく理解できませんでした。

そもそも、量子化のPythonスクリプトを用いる方法[こちら](https://github.com/axinc-ai/export-to-tflite/blob/main/tensorflow2/quantize.py) で精度が出ないので、saved_model の出力の時点で何か間違っているのかもしれません。

現状報告でしたm(__)m

**Comment by kyakuno** [comment]
meanとstdは画像の前処理の値だと思います。例えば、imagenetの前処理を行う場合、下記のような前処理で、値を-1.0 - 1.0に正規化します。
  
```
        mean = np.array([0.485, 0.456, 0.406])
        std = np.array([0.229, 0.224, 0.225])
        image = image / 255.0
        for i in range(3):
            image[:, :, i] = (image[:, :, i] - mean[i]) / std[i]
        return image
```

**Comment by kyakuno** [comment]
meanとstdの値は学習時にどういう設定を使ったによって決まり、meanとstdに合わせた乱数を作ってキャリブレーションしているのではないかと思います。

**Comment by craft-c** [comment]
> 

>

**Comment by craft-c** [comment]
### 現状メモ

int8モデルを用いる推論の際に、
dtype = float にすると、精度がよくなりました。

推論結果をまとめたpdfを添付します。

大きな問題点は無いように思います。
細かい部分を確認した後、PRを起票したいと思います。

[midas_result_0410.pdf](https://github.com/axinc-ai/ailia-models-tflite/files/11188871/midas_result_0410.pdf)
