### ISSUE TITLE
ADD hrnet

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models-tflite#43]
下記のonnxからfloatとint8のtfliteを生成する。
https://github.com/axinc-ai/ailia-models/tree/master/image_segmentation/hrnet_segmentation

**Comment by kyakuno** [comment]
作業手順は下記を参考にしてください。
https://github.com/axinc-ai/ailia-models-tflite/issues/30

**Comment by Akasan** [comment]
## 作業手順
基本的に #30 を参考に実施

1. ONNXモデルをtflite(float)に変換
    - OpenVINOにある`mo.py`を用いてIR形式へ変換
    - openvino2tensorflowを用いてtfliteへ変換
3. サンプルコードの作成
    - ブランチは`feature/add_hrnet`で作業中
    - floatモデルでは所望の結果が得られることを確認
4. COCODatasetsのval2017を使ってtfliteのfloatモデルをint8モデルに変換（2023/3/12開始）

**Comment by Akasan** [comment]
@kyakuno 
現状の報告です。

[こちら](https://github.com/axinc-ai/ailia-models-tflite/issues/43#issuecomment-1465108584)の流れで作業をしており、現在、サンプルプログラムの調整とtfliteモデルの精度検証を行なっているところです。

HRNetの3つのモデルについてそれぞれ[こちら](https://qiita.com/PINTO/items/7a0bcaacc77bb5d6abb1)を参考にONNXからtfliteに変換した結果を使って現在結果確認していますが、かなりぐしゃっとした結果が返ってきている状態です。

現在、再度１からモデルの変換を実施している最中になります。

進捗あり次第、追って連絡させていただきます。

**Comment by Akasan** [comment]
@kyakuno 
もし同じ経験がありましたらご教授いただけますと幸いなのですが、`openvino2tensorflow`を使うときに、以下のようなエラーが途中で表示されます（結果としてファイルは生成されていますが）

```
cannot pickle 'module' object
```

このエラーが発生することによる推論結果への影響があり、それを過去にご経験されている場合は共有いただけますと幸いです

**Comment by Akasan** [comment]
saved_modelからint8に変換するときの前処理で、`/255.0`のところを`/127.5`になっていたので、前者に修正して再度int8への変換を行なっています。

なお、後者の方で前処理を行いできたモデルについて、hrnet_segmentationで/255.0の前処理に修正したところ、画面中部の荒れ方が治りました。
![result_new_int8_oneimage_int8](https://user-images.githubusercontent.com/30067659/225579072-493a204a-d28f-4b71-8927-87e8bd0b5629.png)

まずはint8にする際に前処理を/255に変更したのちに、再度モデルの評価をしようと思います

**Comment by kyakuno** [comment]
いい感じの出力が得られていますね！

**Comment by Akasan** [comment]
この先のTODOについて

- キャリブレーションについて
int8への変換時に多くのキャリブレーションファイルがあればより精度が高くなるということで、可能であれば5000枚全てを使えればなと思いますので、これからする予定です

- video対応
現在、ビデオへの対応（主にWebカメラ映像を用いた検証）をしています。結果の画像が所望のように表示されていない（上記添付の画像のような結果になっていない）ので修正しているところです

**Comment by Akasan** [comment]
@kyakuno 
前処理を/255にし、COCO2017のvalデータでキャリブレーションしたモデルそれぞれを使った結果を添付します。
以下の例では5000枚全てを使ってキャリブレーションしました

## HRNetV2-W48
![HRNetV2-W48_all](https://user-images.githubusercontent.com/30067659/226157205-9665e19c-3b15-4fef-b18b-afc62f52e07d.png)


## HRNetV2-W18-Small-v1
![HRNetV2-W18-Small-v1_all](https://user-images.githubusercontent.com/30067659/226157207-ab0bc8bb-e240-4852-bfd7-333df7eceba1.png)


## HRNetV2-W18-Small-v2
![HRNetV2-W18-Small-v2_all](https://user-images.githubusercontent.com/30067659/226157210-6df3c096-141d-4c35-9ff2-f5903f3fffb1.png)

**Comment by Akasan** [comment]
@kyakuno 
現在、動画対応させるためのコードを作成しております。
ailia-modelsの実装で試していたのですが、動作がうまくいかなかったので、一旦は以下の流れで行っています

1. NumPy → PILにして、putpalette関数によってパレットを適用
2. PIL.Image.saveでテンプ画像に保存
3. opencvで読み込む

ただしこれはかなり冗長な内容なので、修正途中です。
こちらが完了次第、ailia-sdkを用いた最終検証をして、問題なければPRを投げて次のモデルを対応するといった流れになる想定です

**Comment by Akasan** [comment]
上記[動画表示の件](https://github.com/axinc-ai/ailia-models-tflite/issues/43#issuecomment-1476024311)、NumPyで問題なく対応できるようになりました
