### ISSUE TITLE
ADD SRResNet

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models-tflite#45]
srresnetをonnxからtfliteに変換する。
https://github.com/axinc-ai/ailia-models/tree/master/super_resolution/srresnet

**Comment by kyakuno** [comment]
作業手順は下記を参考にしてください。
https://github.com/axinc-ai/ailia-models-tflite/issues/30

**Comment by craft-c** [comment]
###作業内容
・.onnx → .tflite (float32) (int8) 変換作業
・ailia-models-tflite版 SRResNetサンプル 作成

**Comment by craft-c** [comment]
作業メモ

モデル読み込み時のエラーについて

・公式tflite
interpreter = tf.lite.Interpreter(model_path=MODEL_PATH)
pip で tensowflowのバージョンを 2.12.0 まで上げれば解決

・ailia tflite runtime
interpreter = ailia_tflite.Interpreter(model_path=MODEL_PATH)
未解決 ※とりあえず保留
エラー内容
`INFO utils.py (13) : Start!
TFLite file is prepared!
Traceback (most recent call last):
  File ".\srresnet.py", line 278, in <module>
    main()
  File ".\srresnet.py", line 260, in main    
    interpreter = ailia_tflite.Interpreter(model_path=MODEL_PATH) #★
  File "C:\Users\tanikubo\Documents\ailia-models-tf\.ailia-tf\lib\site-packages\ailia_tflite\__init__.py", line 303, in __init__
    self.__check(self.dll.Create(self.instance, self.tflite_cdata, self.tflite_clength, ctypes.c_int32(env_id), ctypes.c_int32(memory_mode), flags))
  File "C:\Users\tanikubo\Documents\ailia-models-tf\.ailia-tf\lib\site-packages\ailia_tflite\__init__.py", line 321, in __check
    raise AiliaTFLiteError(f"ailia tflite runtime error "+detail, status)
ailia_tflite.AiliaTFLiteError: ailia tflite runtime error (Currentry supports 1 to 4 dim shape.) code:-5`

**Comment by craft-c** [comment]
.onnx → .tflite (float) の変換について

・openvino2tensorflow で変換したモデル を用いて推論した結果がよくありません
・onnx2tfをで変換したモデル を用いて推論した結果は良好でした

![image](https://user-images.githubusercontent.com/66067238/227891086-4d08f981-154b-47ae-93fc-6d7dfd9424c9.png)

**Comment by craft-c** [comment]
.onnx → .tflite (float32) (int8) の変換について、
上手に変換できたフロー以下に示します。

なお、quantize.pyは [こちら](https://github.com/axinc-ai/export-to-tflite/blob/main/tensorflow2/quantize.py) のスクリプトを参考にしました。

![image](https://user-images.githubusercontent.com/66067238/228147512-be29b299-2db8-4f9c-9145-d89e69da5a61.png)

**Comment by craft-c** [comment]
@kyakuno 

ailia-tflite runtime でモデルを読み込む部分↓ でエラーが出ます。
interpreter = ailia_tflite.Interpreter(model_path=MODEL_PATH)

エラー内容
```
(.ailia-tf-1.1.7.1) PS C:\Users\tanikubo\Programs\Local\ailia-models-tf\ailia-models-tflite\super_resolution\srresnet> python srresnet.py
 INFO utils.py (13) : Start!
TFLite file is prepared!
Traceback (most recent call last):
  File "srresnet.py", line 282, in <module>
    main()
  File "srresnet.py", line 265, in main
    interpreter = ailia_tflite.Interpreter(model_path=MODEL_PATH)
  File "C:\Users\tanikubo\Programs\_Pkges\venvs\.ailia-tf-1.1.7.1\lib\site-packages\ailia_tflite\__init__.py", line 303, in __init__
    self.__check(self.dll.Create(self.instance, self.tflite_cdata, self.tflite_clength, ctypes.c_int32(env_id), ctypes.c_int32(memory_mode), flags))
  File "C:\Users\tanikubo\Programs\_Pkges\venvs\.ailia-tf-1.1.7.1\lib\site-packages\ailia_tflite\__init__.py", line 321, in __check
    raise AiliaTFLiteError(f"ailia tflite runtime error "+detail, status)
ailia_tflite.AiliaTFLiteError: ailia tflite runtime error (Currentry supports 1 to 4 dim shape.) code:-5
```


AILIA-TFLITE 評価版 を再度インストールして確認しましたが、結果は同じでした。
解決方法が分からず詰まっています。ご教示お願いしたいです。



なお、公式のTFlite では上手く動作します。
また、(float32) 及び(int8) モデル の変換も完了し、良好な推論結果を得られました。
AILIA-TFLITEで上手く動作することを確認できれば、サンプルは完成です。

**Comment by kyakuno** [comment]
現在、ailia tflite runtimeがサポートしているテンソルの次元数は4までとなっています。
どこかでテンソルが5次元になっているのが原因と考えていまして、tfliteをいただくことは可能でしょうか。

**Comment by kyakuno** [comment]
ONNXモデル的には4次元で走りそうではあるのですが、変換の過程か何かで5次元になっていそうな気がします。
https://netron.app/?url=https://storage.googleapis.com/ailia-models/srresnet/srresnet.opt.onnx.prototxt

**Comment by craft-c** [comment]
@kyakuno 

確認したところ、私が変換した.tfliteファイル (float32) において、
入出力が 6次元になっている箇所が見つかりました。

![image](https://user-images.githubusercontent.com/66067238/228421141-80df359a-e0d8-4fff-a259-58972481a114.png)

**Comment by craft-c** [comment]
@kyakuno 

6次元になっている部分のみ修正する方法はあるのでしょうか？
それとも、4次元を超えないように、再び変換方法を見直した方が良いのでしょうか？

**Comment by craft-c** [comment]
@kyakuno 

確認したところ、そもそも変換前のonnxモデル(srresnet.opt.onnx) に6次元の部分がありあした。

![image](https://user-images.githubusercontent.com/66067238/228424683-f45bc69a-5640-4ccb-b625-20683054ebcf.png)

**Comment by craft-c** [comment]
返還前のonnx モデル に6次元の部分が含まれていました。
しかし、.onnx.prototxt の方には 6次元の部分がありませんでした。
同じ内容のファイル？のはずなのに、どうしてでしょうか？ (23/03/29 時点)

![image](https://user-images.githubusercontent.com/66067238/228443631-f5269177-2156-44fd-8610-33d161cbb7dc.png)

)

**Comment by craft-c** [comment]
オプションなど見直して、再度変換を実行しましたが、
6次元の部分が必ず発生します。

**Comment by kyakuno** [comment]
最後のPixelShuffleが、TransposeとReshapeで実装されているみたいですね。
ailia側で対応しますので、一旦、モデルはこのままで、PRをいただけますでしょうか。
公式のtensorflowで動けば問題ありません。
