### ISSUE TITLE
ADD GoogleNet

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models-tflite#57]
https://github.com/axinc-ai/ailia-models/tree/master/image_classification/googlenet

**Comment by craft-c** [comment]
作業内容
・.onnx → .tflite (float32) (int8) 変換作業
・ailia-models-tflite版 GoogleNetサンプル 作成

**Comment by craft-c** [comment]
@kyakuno 

googleNet 量子化(int8)モデルの生成で詰まっています。
ご教示お願いしたいです。

googlenetは画像分類を行うスクリプトです。
スライド1枚目のように、float32モデルの精度は良いのですが、int8モデルの精度が良くありません。
int8モデルへ至る変換フローを、スライド2枚目 に示します。

キャリブレーション画像の問題なのでしょうか？
試しに pizza の画像1枚だけで キャリブレーションを行ったのですが、精度は良くありませんでした。
なにか注意点などございましたら、教えていただきたいです。

![image](https://user-images.githubusercontent.com/66067238/229050268-ec440749-25a0-4652-9242-2b72b124702d.png)
![image](https://user-images.githubusercontent.com/66067238/229050308-f528f333-af86-4bbc-815a-edaaa7102bb3.png)

**Comment by craft-c** [comment]
@kyakuno 

※量子化に使用したスクリプト(quantize.py) も添付しておきます。
※現時点でのサンプルの内容は、GoogleNetブランチから確認できます。[こちら](https://github.com/axinc-ai/ailia-models-tflite/tree/GoogleNet/image_classification/googlenet)
※float32のモデルは [こちら](https://drive.google.com/drive/folders/164UG8huyGlBQ1U1NfDSp9z6pUgxH3yI7?usp=share_link) からダウンロードできます。

現状メモ (23/03/31)
量子化モデル以外の部分は完成しています。

**Comment by kyakuno** [comment]
キャリブレーションに与える画像の入力値のレンジを確認いただければと思います。-1.0 - 1.0か、0 - 255かなどです。また、量子化時にどのようなレンジを与えるかのオプションを探してみてください。

**Comment by craft-c** [comment]
メモ

試しにresnet50 の onnxモデルを、[上記の手順](https://github.com/axinc-ai/ailia-models-tflite/issues/57#issuecomment-1491428768)で量子化したところ、うまくいきました。

**Comment by kyakuno** [comment]
resnet50は0-255かつbgr順、googlenetはnormalize_type=Noneで0-255かつbgr順なので、量子化は問題なさそうな気がしますね。
https://github.com/axinc-ai/ailia-models/blob/master/image_classification/resnet50/resnet50.py
https://github.com/axinc-ai/ailia-models/blob/master/image_classification/googlenet/googlenet.py

**Comment by kyakuno** [comment]
そもそも、テスト画像が微妙な気がしてきましたので、clock.pngを入れてみて、clockが出力されるか確認いただいても良いでしょうか？このpizza画像は、判定が難しい画像な気がします。

**Comment by craft-c** [comment]
clock.jpg を入力した結果です。
結果は honeycomb になってしまいます。
`class_count=3
+ idx=0
  category=599[honeycomb ]
  prob=8.43918514251709
  value=54
+ idx=1
  category=737[pop bottle, soda bottle ]
  prob=5.5038161277771
  value=14
+ idx=2
  category=898[water bottle ]
  prob=5.283663749694824
  value=11
 INFO googlenet_memo.py (166) : Script finished successfully.`

先ほど気づいたのですが、どんな画像を入れても、毎回結果が honeycomb になってしまいます。
prob と value の値も まったく同じです。

**Comment by craft-c** [comment]
なお、floatのモデルでは pizzaの画像もきちんと推論できるので、推論スクリプトの問題ではないと思います。

**Comment by kyakuno** [comment]
サンプルの、dtype = np.int8を、dtype = np.floatにしないといけない気がします。/255すると、全て0になっていまいそうです。

**Comment by craft-c** [comment]
clock.jpg を入力した結果です。
やはり、結果は honeycomb になってしまいます。

`class_count=3
+ idx=0
  category=599[honeycomb ]
  prob=8.43918514251709   
  value=54
+ idx=1
  category=737[pop bottle, soda bottle ]
  prob=5.5038161277771
  value=14
+ idx=2
  category=898[water bottle ]
  prob=5.283663749694824
  value=11
 INFO googlenet_memo.py (166) : Script finished successfully.`

**Comment by craft-c** [comment]
@kyakuno 

int8モデルで精度出ない問題について、
おそらくモデルが原因なので、再度モデル変換を試みているのですが、
現在、以下の状況で詰まっています。
お目通しお願いしたいです。


onnx2tfを用いてモデル変換する方法
→ float32モデルは推論精度良好
→ quantize.pyで量子化したモデルは、どの画像を入力しても、毎回出力が "honeycomb" になってしまう
　(推論スクリプトの、dtype = np.int8は、dtype = floatに変更済みです)

openvino2tensorflowを用いてモデル変換する方法
→ openvinoからsaved_mmodelへ変換するときにエラーが出る
`ValueError: Input 0 of layer "zero_padding2d" is incompatible with the layer: expected ndim=4, found ndim=5. Full shape received: (1, 3, 1, 224, 3)`
`ERROR: Please refer to 6-7 in the README first. https://github.com/PINTO0309/openvino2tensorflow`
エラーで示されたURL先([こちら](https://github.com/PINTO0309/openvino2tensorflow#6-7-replace-weights-or-constant-values-in-const-op-and-add-transpose-or-reshape-or-cast-or-squeeze-or-unsqueeze-or-add-or-multiply-just-beforeafter-the-operation-specified-by-layer_id)) によると、JSONファイルを用いて強制的にConstの内容を変更できるとのこと。
つまり、変換前の.onnxモデルで、次元の要素数が5になっている部分を強制的に4に変更すれば良いのでしょうか？
しかし、googlenet.onnx を Netronで開いて確認してみたが、5次元になっている部分を見つけられません。

なお、googlenet.onnx　は、[こちら](https://storage.googleapis.com/ailia-models/googlenet/googlenet.onnx) から入手できます。

**Comment by craft-c** [comment]
@kyakuno 

[量子化モデルについて]

[[こちら]](https://cyberagent.ai/blog/tech/17657/)の記事で紹介されていた、onnx2tflite[[こちら]](https://github.com/MPolaris/onnx2tflite) という onnx2tfの類似ツールを用いて量子化モデルを生成した結果、精度が良くなりました。
この変換ツールを使用するのは問題ないでしょうか？
onnx2tfliteの仕様の不足点については、記事中でいくつか言及されていましたが、googlenetのモデルに関しては良い精度が得られました。

問題ないようでしたら、PRしたいと思います。


float32 及び、int8 モデルは[[こちら]](https://drive.google.com/drive/folders/164UG8huyGlBQ1U1NfDSp9z6pUgxH3yI7?usp=share_link)からDLできます。
また、作成したサンプルはgooglenetブランチ[[こちら]](https://github.com/axinc-ai/ailia-models-tflite/tree/GoogleNet/image_classification/googlenet)から確認できます。

![image](https://user-images.githubusercontent.com/66067238/233032641-4ccbc8b0-02a0-463d-a9dd-9f69f9f18785.png)

**Comment by kyakuno** [comment]
はい、onnx2tfliteを使用いただいて問題ありません。
PRをお願いします。
